# name: seqovl — перекрытие TCP-последовательности
# note: против DPI, который собирает поток целиком
# ports_tcp: 80,443
# ports_udp: 443
--filter-tcp=80,443 --filter-l7=tls,http --payload=tls_client_hello --lua-desync=fake:blob=fake_default_tls:tcp_md5:tls_mod=rnd,rndsni,dupsid --payload=http_req --lua-desync=fake:blob=fake_default_http:tcp_md5 --payload=tls_client_hello,http_req --lua-desync=multisplit:pos=1:seqovl=5:seqovl_pattern=0x1603030000
