# name: quic-only — дурим только QUIC
# note: когда TCP уже работает, а видео по UDP тормозит
# ports_tcp: 80,443
# ports_udp: 443
--filter-udp=443 --filter-l7=quic --payload=quic_initial --lua-desync=fake:blob=fake_default_quic:repeats=6:ip_autottl=-2,3-20
